
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-13
owner: ucsb-cs156-s25
repo_name: team02-s25-13
pull_requests: [{"author":{"id":"U_kgDOCM8Qxw","is_bot":false,"login":"k-nn-tht","name":"Kenneth Tan"},"headRefName":"Kenneth-RecommendationRequest-edit_page","number":91,"title":"Kenneth recommendation request edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/91"},{"author":{"id":"U_kgDOCM8Qxw","is_bot":false,"login":"k-nn-tht","name":"Kenneth Tan"},"headRefName":"Kenneth-RecommendationRequest-index_page","number":90,"title":"Kenneth recommendation request index page","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/90"},{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"tuan-articles-index-page","number":89,"title":"Tuan - Articles Index Page","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/89"},{"author":{"id":"U_kgDOCM8Qxw","is_bot":false,"login":"k-nn-tht","name":"Kenneth Tan"},"headRefName":"Kenneth-RecommendationRequest-create_page","number":88,"title":"Kenneth recommendation request create page","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/88"},{"author":{"id":"U_kgDOCI505Q","is_bot":false,"login":"chengcxi","name":""},"headRefName":"helprequest-chengcxi","number":84,"title":"form & tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/84"}]
