
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-13
owner: ucsb-cs156-s25
repo_name: team02-s25-13
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"tuan-articles-e2e-tests","number":116,"title":"Tuan - Articles End-To-End Tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/116"},{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"tuan-articles-integration-tests","number":113,"title":"Tuan articles integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/113"}]
