
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-13
owner: ucsb-cs156-s25
repo_name: team02-s25-13
pull_requests: [{"author":{"id":"U_kgDOCM8Qxw","is_bot":false,"login":"k-nn-tht","name":"Kenneth Tan"},"headRefName":"Kenneth-RecommendationRequest-table","number":81,"title":"Kenneth recommendation request table","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/81"},{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"tuan-article-placeholder-pages","number":80,"title":"Tuan - Article Placeholder Pages ","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/80"},{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"tuan-articles-table","number":79,"title":"Tuan - Articles Table","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/79"},{"author":{"id":"U_kgDOCM8Qxw","is_bot":false,"login":"k-nn-tht","name":"Kenneth Tan"},"headRefName":"Kenneth-RecommendationRequest-form","number":78,"title":"Kenneth recommendation request form","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/78"},{"author":{"id":"U_kgDOCM7m-A","is_bot":false,"login":"timothytwu","name":""},"headRefName":"timothy-menuitemreview-table","number":77,"title":"Timothy  - menuitemreview table","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/77"},{"author":{"id":"MDQ6VXNlcjMwNDIwNTE0","is_bot":false,"login":"nikunjparasar","name":"Nikunj Parasar"},"headRefName":"np-form-menuitem-component","number":75,"title":"np -  form menuitem component","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/75"},{"author":{"id":"MDQ6VXNlcjY1MDUwMDUz","is_bot":false,"login":"connersiou","name":""},"headRefName":"Conner-UCSBOrganization-form","number":74,"title":"Conner - create form for UCSBOrganization database","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/74"},{"author":{"id":"U_kgDOCM7m-A","is_bot":false,"login":"timothytwu","name":""},"headRefName":"timothy-menuitemreview-form","number":73,"title":"Timothy menuitemreview form","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/73"},{"author":{"id":"U_kgDOCI505Q","is_bot":false,"login":"chengcxi","name":""},"headRefName":"helprequest-chengcxi","number":68,"title":"Copy files for Backend CRUD API","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/68"}]
