
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-13
owner: ucsb-cs156-s25
repo_name: team02-s25-13
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"tuan-Articles-fixtures","number":67,"title":"Added fixtures for Articles","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/67"},{"author":{"id":"U_kgDOCM8Qxw","is_bot":false,"login":"k-nn-tht","name":"Kenneth Tan"},"headRefName":"Kenneth-RecommendationRequest-backend","number":66,"title":"kt - copied rec req backend files","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/66"},{"author":{"id":"U_kgDOCM7m-A","is_bot":false,"login":"timothytwu","name":""},"headRefName":"timothy-menuitemreview-fixtures","number":65,"title":"Timothy - create menuitemreview fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/65"},{"author":{"id":"MDQ6VXNlcjY1MDUwMDUz","is_bot":false,"login":"connersiou","name":""},"headRefName":"Conner-UCSBOrganization-fixtures","number":63,"title":"Conner - create fixtures for UCSBOrganization database","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/63"}]
