
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-13
owner: ucsb-cs156-s25
repo_name: team02-s25-13
pull_requests: [{"author":{"id":"MDQ6VXNlcjMwNDIwNTE0","is_bot":false,"login":"nikunjparasar","name":"Nikunj Parasar"},"headRefName":"np-edit-menuitems-page","number":104,"title":"np - edit menuitems page","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/104"},{"author":{"id":"MDQ6VXNlcjMwNDIwNTE0","is_bot":false,"login":"nikunjparasar","name":"Nikunj Parasar"},"headRefName":"np-menuitem-index-page","number":103,"title":"np -  menuitem index page","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/103"},{"author":{"id":"MDQ6VXNlcjMwNDIwNTE0","is_bot":false,"login":"nikunjparasar","name":"Nikunj Parasar"},"headRefName":"np-menuitem-working-create-page","number":102,"title":"np - working create page for UCSBDiningCommonsMenuItems","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/102"},{"author":{"id":"U_kgDOCI505Q","is_bot":false,"login":"chengcxi","name":""},"headRefName":"helprequest-chengcxi","number":101,"title":"helprequest pages","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/101"},{"author":{"id":"MDQ6VXNlcjMwNDIwNTE0","is_bot":false,"login":"nikunjparasar","name":"Nikunj Parasar"},"headRefName":"np-create-placeholder-page","number":100,"title":"np - add placeholder pages for Index, Edit, Create for UCSBDIningCommonsMenuItems","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/100"},{"author":{"id":"MDQ6VXNlcjY1MDUwMDUz","is_bot":false,"login":"connersiou","name":""},"headRefName":"Conner-UCSBOrganization-edit-page","number":97,"title":"Conner - add correct logic for UCSBOrganization Edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-13/pull/97"}]
